# Generated by Django 5.0 on 2024-09-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaluser',
            name='name',
        ),
    ]
