# Generated by Django 5.0 on 2024-09-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcheck', '0002_remove_externaluser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustcheck.datatype'),
        ),
    ]
