# Generated by Django 5.0 on 2024-10-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcheck', '0003_datatype_datasubmission_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent DataType for hierarchical categorization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_data_types', to='trustcheck.datatype'),
        ),
    ]
