# Generated by Django 5.0 on 2024-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcheck', '0005_alter_category_name_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
